use crate::game::board::Position;

/// Empty board state
pub const EMPTY_BOARD: &str = "1/3/5/7/9/11/11/11/11/11/11";

/// Empty board state
pub const EMPTY_HEXCHESS: &str = "1/3/5/7/9/11/11/11/11/11/11 w - 0 1";

/// Initial hexchess state
pub const INITIAL_BOARD: &str = "b/qbk/n1b1n/r5r/ppppppppp/11/5P5/4P1P4/3P1B1P3/2P2B2P2/1PRNQBKNRP1";

/// Initial hexchess state
pub const INITIAL_HEXCHESS: &str = "b/qbk/n1b1n/r5r/ppppppppp/11/5P5/4P1P4/3P1B1P3/2P2B2P2/1PRNQBKNRP1 w - 0 1";

/// positions sorted by fen order
pub const SORTED_POSITIONS: [Position; 91] = [
    Position::F11,
    Position::E10,
    Position::F10,
    Position::G10,
    Position::D9,
    Position::E9,
    Position::F9,
    Position::G9,
    Position::H9,
    Position::C8,
    Position::D8,
    Position::E8,
    Position::F8,
    Position::G8,
    Position::H8,
    Position::I8,
    Position::B7,
    Position::C7,
    Position::D7,
    Position::E7,
    Position::F7,
    Position::G7,
    Position::H7,
    Position::I7,
    Position::K7,
    Position::A6,
    Position::B6,
    Position::C6,
    Position::D6,
    Position::E6,
    Position::F6,
    Position::G6,
    Position::H6,
    Position::I6,
    Position::K6,
    Position::L6,
    Position::A5,
    Position::B5,
    Position::C5,
    Position::D5,
    Position::E5,
    Position::F5,
    Position::G5,
    Position::H5,
    Position::I5,
    Position::K5,
    Position::L5,
    Position::A4,
    Position::B4,
    Position::C4,
    Position::D4,
    Position::E4,
    Position::F4,
    Position::G4,
    Position::H4,
    Position::I4,
    Position::K4,
    Position::L4,
    Position::A3,
    Position::B3,
    Position::C3,
    Position::D3,
    Position::E3,
    Position::F3,
    Position::G3,
    Position::H3,
    Position::I3,
    Position::K3,
    Position::L3,
    Position::A2,
    Position::B2,
    Position::C2,
    Position::D2,
    Position::E2,
    Position::F2,
    Position::G2,
    Position::H2,
    Position::I2,
    Position::K2,
    Position::L2,
    Position::A1,
    Position::B1,
    Position::C1,
    Position::D1,
    Position::E1,
    Position::F1,
    Position::G1,
    Position::H1,
    Position::I1,
    Position::K1,
    Position::L1,
];
