name: build

on:
  push:
    branches: ["codecov"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cargo build
      run: cargo build --verbose

    - name: Cargo test
      run: cargo test --verbose

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Install dependencies
      run: pnpm install

    - name: Vitest
      run: |
        pnpm i
        pnpm build
        pnpm test

  coverage:
    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate code coverage
      run: |
        cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
