name: build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust

    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test
      run: cargo test

  wasm:
    name: WASM

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'

    - name: Install dependencies
      run: pnpm install

    - name: Build wasm package
      run: pnpm build
    
    - name: TypeScript tests
      run: pnpm test

    - name: Release
      run: |
        cd ./pkg
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
